start_year: 2020
start_month: 1
start_day: 1
end_year: 2020
end_month: 1
end_day: 6

north_latitude: 80
south_latitude: 40
west_longitude: -30
east_longitude: 20

cdskey:
  class: File
  path: ../.cdsapirc

https_proxy: "http://proxy.man.ac.uk:3128"
